### ISSUE TITLE
Split Phoenix & Elixir Image

### ISSUE THREAD

**Issue by maennchen** [openshift-s2i/s2i-phoenix#6]
In my opinion it would make sense to build an elixir base S2I Image and add a phoenix one on top.

Would you welcome a contribution into this direction?

**Comment by jawnsy** [comment]
@maennchen Not knowing much about Phoenix or Elixir (this work was contributed by @jtslear), that makes sense to me! We'd definitely welcome that contribution, I suggest starting by creating a stand-alone Elixir image as a first step. :smile:

**Comment by maennchen** [comment]
Great, I'll look into it soon.

**Comment by jtslear** [comment]
I also think this is a great idea.
